
// Car/Car
export const ADD_CAR = 'ADD_CAR'
export const DELETE_CAR = 'DELETE_CAR'
export const SET_USER_CARS = 'SET_USER_CARS'
export const SEARCHED_CAR = 'SEARCHED_CAR'

export const ADD_TIMELINE = 'ADD_TIMELINE'
export const ADD_TIMELINE_ITEM = 'ADD_TIMELINE_ITEM'
export const DELETE_TIMELINE_ITEM = 'DELETE_TIMELINE_ITEM'
export const UPDATE_TIMELINE_ITEM = 'UPDATE_TIMELINE_ITEM'
export const DELETE_STATUS = 'DELETE_STATUS'
export const UPDATE_STATUS = 'UPDATE_STATUS'
export const DELETE_IMAGE = 'DELETE_IMAGE'
export const DELETE_TIMELINE_VIDEO = 'DELETE_TIMELINE_VIDEO'
export const UPDATE_TIMELINE_VIDEO = 'UPDATE_TIMELINE_VIDEO'
export const PLAY_TIMELINE_VIDEO = 'PLAY_TIMELINE_VIDEO'
export const PAUSE_TIMELINE_VIDEO = 'PAUSE_TIMELINE_VIDEO'

export const ADD_COMMENTS = 'ADD_COMMENTS'
export const ADD_TIMELINE_COMMENT = 'ADD_TIMELINE_COMMENT'
export const ADD_TIMELINE_COMMENTS = 'ADD_TIMELINE_COMMENTS'

export const SET_USER_LIKED_ITEMS = 'SET_USER_LIKED_ITEMS'
export const LIKE_TIMELINE_ITEM = 'LIKE_TIMELINEL_ITEM'

export const UPDATE_USER_CAR_IMAGES = 'UPDATE_USER_CAR_IMAGES'
export const UPDATE_USER_CAR_VIDEOS = 'UPDATE_USER_CAR_VIDEOS'

// Auth
export const INVALIDATE_USER = 'INVALIDATE_USER'
export const SET_AUTH = 'SET_AUTH'
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR'
export const ATTEMPT_OIDC_AUTH = 'ATTEMPT_OIDC_AUTH'

export const SET_USER = 'SET_USER'
export const SET_USER_FOLLOW_COUNT =  'SET_USER_FOLLOW_COUNT'
export const SET_USER_CAR_COUNT =  'SET_USER_CAR_COUNT'

// State
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS'
export const UNSET_LOADING_STATUS = 'UNSET_LOADING_STATUS'

// Dialog
export const CONFIRM_ACTION = 'CONFIRM_ACTION'
export const REMOVE_CONFIRM = 'REMOVE_CONFIRM'
export const SET_FLASH = 'SET_FLASH'
export const CLEAR_FLASH = 'CLEAR_FLASH'

// Search
export const CARS_SEARCHED = 'CARS_SEARCHED'